
from django.urls import include, path

from clinic import  PharmacistView, editView, imports



urlpatterns = [
        path('save_prescription/<int:patient_id>/<int:visit_id>/', PharmacistView.save_prescription, name='pharmacist_save_prescription'),
        path('save_laboratory/<int:patient_id>/<int:visit_id>/', PharmacistView.save_laboratory, name='pharmacist_save_laboratory'),
        path('save_remotereferral/<int:patient_id>/<int:visit_id>/', PharmacistView.save_remotereferral, name='pharmacist_save_remotereferral'),
        path('save_remoteprocedure/<int:patient_id>/<int:visit_id>/', PharmacistView.save_remoteprocedure, name='pharmacist_save_remoteprocedure'),
        path('save_observation/<int:patient_id>/<int:visit_id>/', PharmacistView.save_observation, name='pharmacist_save_observation'),
        path('verify_prescriptions/', PharmacistView.verify_prescriptions, name='pharmacist_verify_prescriptions'),
        path('unverify_prescriptions/', PharmacistView.unverify_prescriptions, name='pharmacist_unverify_prescriptions'),
        path('issue_prescriptions/', PharmacistView.issue_prescriptions, name='pharmacist_issue_prescriptions'),
        path('unissue_prescriptions/', PharmacistView.unissue_prescriptions, name='pharmacist_unissue_prescriptions'),        
        path('update_payment_status/', PharmacistView.update_payment_status, name='pharmacist_pay_prescriptions'),
        path('unpay_prescriptions/', PharmacistView.unpay_prescriptions, name='pharmacist_unpay_prescriptions'),
        path('new_lab_order/', PharmacistView.new_lab_order, name='pharmacist_new_lab_order'),
        path('add_investigation/', PharmacistView.add_investigation, name='pharmacist_add_investigation'),
        path('add_imaging/', PharmacistView.add_imaging, name='pharmacist_add_imaging'),
        path('manage_disease/', PharmacistView.manage_disease, name='pharmacist_manage_disease'),
        path('ambulance_order/', PharmacistView.ambulance_order_create_or_update, name='ambulance_order_create_or_update'),
        path('ambulance_order/<int:order_id>/', PharmacistView.ambulance_order_create_or_update, name='ambulance_order_edit'),
        path('update_orderpayment_status/', PharmacistView.update_orderpayment_status, name='update_orderpayment_status'),
        path('invoice/<int:order_id>/', PharmacistView.generate_invoice_bill, name='pharmacist_generate_invoice_bill'),
        path('prescriptions/<str:visit_number>/<int:patient_id>/', PharmacistView.prescription_detail, name='pharmacist_prescription_detail'),
        path('patients/<int:patient_id>/visits/<int:visit_id>/ambulance_order/', PharmacistView.save_ambulance_order, name='save_ambulance_order'),
        path('patients/<int:patient_id>/visits/<int:visit_id>/ambulance_order/<int:ambulance_id>/', PharmacistView.save_ambulance_order, name='edit_ambulance_order'),
        path('new_consultation_order/', PharmacistView.new_consultation_order, name='pharmacist_new_consultation_order'),
        path('add_consultation/', PharmacistView.add_consultation, name='pharmacist_add_consultation'),
        path('new_radiology_order/', PharmacistView.new_radiology_order, name='pharmacist_new_radiology_order'),
        path('new_procedure_order/', PharmacistView.new_procedure_order, name='pharmacist_new_procedure_order'),
        path('add_procedure/', PharmacistView.add_procedure, name='pharmacist_add_procedure'),
        path('get-procedure-cost/', PharmacistView.get_procedure_cost, name='pharmacist_get_procedure_cost'),   
        path('pharmacist_dashboard/', PharmacistView.pharmacist_dashboard, name='pharmacist_dashboard'),    
        path('add_patient/', PharmacistView.add_patient, name='pharmacist_add_patient'),
        path('delete_ambulancecardorder/', PharmacistView.delete_ambulancecardorder, name='delete_ambulancecardorder'),
        path('delete_ambulancedorder/', PharmacistView.delete_ambulancedorder, name='delete_ambulancedorder'),
        path('vehicle_detail/<int:order_id>/', PharmacistView.vehicle_detail, name='vehicle_detail'),    
        path('vehicle_ambulance_view/',PharmacistView.vehicle_ambulance_view, name="pharmacist_vehicle_ambulance_view"),        
        path('ambulance_order_detail/<int:order_id>/', PharmacistView.ambulance_order_detail, name='pharmacist_ambulance_order_detail'),        
        path('get_unit_price/',PharmacistView.get_unit_price, name="pharmacist_get_unit_price"),
        path('ambulance_order_view/',PharmacistView.ambulance_order_view, name="pharmacist_ambulance_order_view"),     
        path('add_remoteprescription/',PharmacistView.add_remoteprescription, name="pharmacist_add_remoteprescription"),
        path('save_patient_vital/',PharmacistView.save_patient_vital, name="pharmacist_save_patient_vital"),
        path('add_prescription/',PharmacistView.add_prescription, name="pharmacist_add_prescription"),
        path('save_edited_patient/',PharmacistView.save_edited_patient, name="pharmacist_save_edited_patient"),
        path('add_patient_visit/',PharmacistView.add_patient_visit, name="pharmacist_add_patient_visit"),      
        path('accounts/', include('django.contrib.auth.urls')),         
        path('staff_detail/<int:staff_id>/', PharmacistView.single_staff_detail, name='pharmacist_single_staff_detail'),
        path('view-patient/<int:patient_id>/', PharmacistView.view_patient, name='pharmacist_view_patient'),  
        path('save_service_data/',PharmacistView.save_service_data, name="pharmacist_save_service_data"),      
        path('get_item_quantity/',PharmacistView.get_item_quantity, name="pharmacist_get_item_quantity"),        
        path('resa/patient_vital_all_listt/', PharmacistView.patient_vital_all_list, name='pharmacist_patient_vital_all_list'),
        path('patient_consultation_detail/<int:patient_id>/<int:visit_id>/', PharmacistView.patient_consultation_detail, name='pharmacist_patient_consultation_detail'),
        path('patient_vital_list/<int:patient_id>/', PharmacistView.patient_vital_list, name='pharmacist_patient_vital_list'),
        path('patient_health_record/<int:patient_id>/<int:visit_id>/', PharmacistView.patient_health_record, name='pharmacist_patient_health_record'),
        path('patient_vital_visit_list/<int:patient_id>/<int:visit_id>/', PharmacistView.patient_vital_visit_list, name='pharmacist_patient_vital_visit_list'),
        path('patient_visit_history/<int:patient_id>/', PharmacistView.patient_visit_history_view, name='pharmacist_patient_visit_history_view'),       
        path('prescriptions/', PharmacistView.prescription_list, name='pharmacist_prescription_list'),       
        path('resa/manage-referral/', PharmacistView.manage_referral, name='pharmacist_manage_referral'),
        path('resa/patient-procedure-view/', PharmacistView.patient_procedure_view, name='pharmacist_patient_procedure_view'),      
        path('resa/all-patients',PharmacistView.manage_patients, name="pharmacist_manage_patients"),
        path('resa/consultation-queue',PharmacistView.manage_consultation, name="pharmacist_manage_consultation"),
        path('resa/manage-service',PharmacistView.manage_service, name="pharmacist_manage_service"),
        path('resa/appointments/', PharmacistView.appointment_list_view, name='pharmacist_appointment_list'),
        path('notifications/', PharmacistView.notification_view, name='pharmacist_notification_view'),
        path('add_disease/', PharmacistView.add_disease, name='pharmacist_add_disease'),
        path('medicine_list/', PharmacistView.medicine_list, name='pharmacist_medicine_list'),
        path('medicine_inventory_list/', PharmacistView.medicine_inventory_list, name='pharmacist_medicine_inventory_list'),
        path('medicine_expired_list/', PharmacistView.medicine_expired_list, name='pharmacist_medicine_expired_list'),
        path('in_stock_medicines_view/', PharmacistView.in_stock_medicines_view, name='pharmacist_in_stock_medicines_view'),
        path('out_of_stock_medicines_view/', PharmacistView.out_of_stock_medicines_view, name='pharmacist_out_of_stock_medicines_view'),
        path('out_of_stock_medicines/', PharmacistView.out_of_stock_medicines, name='pharmacist_out_of_stock_medicines'),
        path('generate-bill/<int:procedure_id>/', PharmacistView.generate_billing, name='pharmacist_generate_billing'),
        path('disease-records/<int:disease_id>/edit/', PharmacistView.edit_disease_record, name='pharmacist_edit_disease_record'),
        path('disease-records/<int:disease_id>/delete/', PharmacistView.delete_disease_record, name='pharmacist_delete_disease_record'),
        path('save_procedure/', PharmacistView.save_procedure, name='pharmacist_save_procedure'),
        path('save_referral/', PharmacistView.save_referral, name='pharmacist_save_referral'),
        path('all_orders_view/', PharmacistView.all_orders_view, name='pharmacist_all_orders_view'),
        path('change_referral_status/', PharmacistView.change_referral_status, name='pharmacist_change_referral_status'),       
        # imports urls 
        
        path('resa/ImportExcel_service',imports.import_service_records, name="pharmacist_import_service_records"),     
        path('import_prescription_records', imports.import_prescription_records, name='pharmacist_import_prescription_records'),
        path('import-patients/', imports.import_patient_records, name='pharmacist_import_patient_records'),    
        path('import-procedure-records/', imports.import_procedure_records, name='pharmacist_import_procedure_records'),
        path('import-referral-records/', imports.import_referral_records, name='pharmacist_import_referral_records'), 
        path('import_disease_recode/', imports.import_disease_recode, name='pharmacist_import_disease_recode'), 
             
        # edit urls        
       
        path('edit-patient-disease-save/<int:patient_disease_id>/edit/', editView.edit_patient_disease_save, name='pharmacist_edit_patient_disease_save'),
        path('update_consultation_data/<int:appointment_id>/', editView.update_consultation_data, name='pharmacist_update_consultation_data'), 
        path('Patient/<int:patient_id>/edit/', editView.edit_patient, name='pharmacist_edit_patient'),
        path('edit_procedure/', editView.edit_procedure, name='pharmacist_edit_procedure'), 
        path('edit_referral/', editView.edit_referral, name='pharmacist_edit_referral'), 
        path('appointment_view/', PharmacistView.appointment_view, name='pharmacist_appointment_view'), 
        path('patient-procedure-history/<str:mrn>/view/', PharmacistView.patient_procedure_history_view, name='pharmacist_patient_procedure_history_view_mrn'), 

              
]
