"""
Django settings for resaclinic project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e5o9&!5%5@2_@j2r3a5t88ytnph2p9%or&gedz=vjitwsg**&*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['3.92.136.150','127.0.0.1','resa.mujtabahschool.ac.tz','www.resa.mujtabahschool.ac.tz']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'clinic',
    'centric',
    'kahamahmis',
    'wkhtmltopdf',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'clinic.LoginCheckMiddleWare.LoginCheckMiddleWare',
    
  
]

ROOT_URLCONF = 'resaclinic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'resaclinic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE':'django.db.backends.mysql',
        'NAME':'resagroup',
        'USER':'root',
        'PASSWORD':'m2r3i4s8',            
        'HOST':'localhost',
        'PORT':'3307',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'clinic.CustomUser'
AUTHENTICATION_BACKENDS = ['clinic.emailBackEnd.EmailBackend']
# EMAIL_BACKEND = "django.core.mail.backends.bdtvjjdagryvnqeb.filebased.EmailBackend"
# EMAIL_FILE_PATH = os.path.join(BASE_DIR,"sent_emails")
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'mrishohamisi1998@gmail.com'
EMAIL_HOST_PASSWORD = 'rtnwirbujomgbjsh'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,"media")


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR,"static")
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]


CKEDITOR_5_FILE_STORAGE = "clinic.storage.CustomStorage"
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}


JAZZMIN_SETTINGS = {
    # Title of the window
    "site_title": "Resa Clinic ",

    # Title on the login screen
    "site_header": "Resa Clinic ",
   
    "index_title":"Dashboard",
    # Title on the brand
    "site_brand": "Resa Clinic ",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "dist/img/resalogo.png",

    # Welcome text on the login screen
    "welcome_sign": "Resa Clinic ",

    # CSS classes that are applied to the logo
    "site_logo_classes": "img-circle",

    # Copyright on the footer
    "copyright": "Resa Medical Group",

    # Relative path to a favicon for your site
    "site_icon": None,

    # Links to put along the top menu
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index"},
        # {"name": "Support", "url": "tour_category_list", "new_window": False},
        {"model": "tourist.Tourist"},

    ],

    # Additional links to include in the user menu on the top right
    "usermenu_links": [
        # {"name": "Support", "url": "activity_list", "new_window": False},
    ],

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to auto-expand the menu
    "navigation_expanded": True,

    # Hide these models when generating side menu
    "hide_models": [],
    
     
    
    # Custom icons for side menu apps/models
"icons": {
    # Auth app icons
    "auth": "fas fa-users-cog",
    "auth.user": "fas fa-user",
    "auth.Group": "fas fa-users",

    # Admin app icons
    "admin.LogEntry": "fas fa-file",

    # Clinic icons
    "clinic.SalaryPayment": "fas fa-money-check",
    "clinic.Payroll": "fas fa-money-bill",
    "clinic.BankAccount": "fas fa-university",
    "clinic.Employee": "fas fa-user-tie",
    "clinic.DeductionOrganization": "fas fa-chart-bar",
    "clinic.EmployeeDeduction": "fas fa-hand-holding-usd",
    "clinic.SalaryChangeRecord": "fas fa-file-alt",
    "clinic.PaymentMethod": "fas fa-credit-card",
    "clinic.ExpenseCategory": "fas fa-list-alt",
    "clinic.Expense": "fas fa-money-bill-alt",
    "clinic.Invoice": "fas fa-receipt",
    "clinic.Payment": "fas fa-money-check-alt",
    "clinic.Client": "fas fa-users",
},

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    # Order apps automatically, but make sure choice and book admin links are first within the books app
   "order_with_respect_to": ["clinic.Employee", "clinic.Payroll", "clinic.SalaryPayment"],
   
    # Render out the change view as a single form, or in tabs
    "changeform_format": "horizontal_tabs",

    # Add a language dropdown into the admin
    "language_chooser": True,

    # Relative paths to custom CSS/JS scripts
    "custom_css": None,
    "custom_js": None,

    # Whether to link font from fonts.googleapis.com
    "use_google_fonts_cdn": True,

    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
   
    "theme": "slate",
}