# Generated by Django 4.2.9 on 2024-01-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='address',
        ),
    ]
