# Generated by Django 4.2.9 on 2024-02-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, verbose_name='Test Name')),
                ('result', models.TextField(blank=True, verbose_name='Test Result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_number', models.CharField(max_length=10, unique=True, verbose_name='Lab Number')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remoteconsultationnotes')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits')),
            ],
        ),
    ]
