# Generated by Django 4.2.9 on 2024-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_imagingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingrecord',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
