# Generated by Django 4.2.9 on 2024-02-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
