# Generated by Django 4.2.9 on 2024-02-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_labtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.diagnosis'),
        ),
    ]
