# Generated by Django 4.2.9 on 2024-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_patientvital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvital',
            name='unique_identifier',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
