# Generated by Django 4.2.9 on 2024-01-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_patient_weekly_exercise_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecordconsultation',
            name='pathology',
        ),
        migrations.RemoveField(
            model_name='medicalrecordconsultation',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='MedicalRecordConsultation',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
