# Generated by Django 4.2.9 on 2024-02-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_labtest_lab_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteprocedure',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.remoteconsultationnotes'),
        ),
        migrations.AlterField(
            model_name='remoteprocedure',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs'),
        ),
    ]
