# Generated by Django 4.2.9 on 2024-03-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_laboratoryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='referral',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patientvisits'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='source_location',
            field=models.CharField(default='resa medical hospital', help_text='Source location of the patient', max_length=255),
        ),
    ]
