# Generated by Django 4.2.9 on 2024-02-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remoteprocedure_consultation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_location', models.CharField(help_text='Source location of the patient', max_length=255)),
                ('destination_location', models.CharField(help_text='Destination location for MedEvac', max_length=255)),
                ('rfn', models.CharField(editable=False, max_length=20, unique=True)),
                ('reason', models.TextField()),
                ('referral_date', models.DateField(auto_now_add=True, help_text='Date when the referral was made')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the referral', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.remoteconsultationnotes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits')),
            ],
        ),
    ]
