# Generated by Django 4.2.9 on 2024-02-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_patientvital_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvital',
            name='avpu',
            field=models.CharField(blank=True, help_text='AVPU scale measurement', max_length=20, null=True),
        ),
    ]
