# Generated by Django 4.2.9 on 2024-01-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_medicalrecordconsultation_pathology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('nationality', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('patient_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.CharField(max_length=255)),
                ('history_illness', models.TextField()),
                ('physical_examination', models.TextField()),
                ('allergy_medications', models.TextField()),
                ('provisional_diagnosis', models.TextField()),
                ('final_diagnosis', models.TextField()),
                ('plan', models.TextField()),
                ('injury', models.CharField(max_length=200)),
                ('fatality', models.CharField(max_length=200)),
                ('injury_description', models.TextField()),
                ('disposition', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=255)),
                ('disposition_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pathology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.pathodologyrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
    ]
