# Generated by Django 4.2.9 on 2024-02-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_patientvital_avpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemotePatientVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vst', models.CharField(editable=False, max_length=20, unique=True)),
                ('visit_type', models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency'), ('Referral', 'Referral'), ('Follow up', 'Follow up')], max_length=15)),
                ('visit_reason', models.TextField(blank=True, null=True)),
                ('primary_service', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
        ),
        migrations.CreateModel(
            name='ConsultationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaints', models.TextField(blank=True, null=True)),
                ('history_of_presenting_illness', models.TextField(blank=True, null=True)),
                ('consultation_number', models.CharField(max_length=20, unique=True)),
                ('physical_examination', models.TextField(blank=True, null=True)),
                ('allergy_to_medications', models.CharField(blank=True, max_length=255, null=True)),
                ('provisional_diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('final_diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_plan', models.TextField()),
                ('injury', models.CharField(blank=True, max_length=100, null=True)),
                ('fatality', models.CharField(blank=True, max_length=100, null=True)),
                ('injury_description', models.TextField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('transport_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('disposition_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs')),
                ('pathology', models.ManyToManyField(blank=True, to='clinic.pathodologyrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
            ],
        ),
    ]
