# Generated by Django 4.2.9 on 2024-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_remotepatientvisits_consultationnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='disposition_description',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='fatality',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='injury',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='injury_description',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='transport_mode',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='final_diagnosis',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='provisional_diagnosis',
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='final_diagnosis',
            field=models.ManyToManyField(blank=True, related_name='final_diagnosis_notes', to='clinic.diagnosis'),
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='provisional_diagnosis',
            field=models.ManyToManyField(blank=True, related_name='provisional_diagnosis_notes', to='clinic.diagnosis'),
        ),
    ]
