# Generated by Django 4.2.9 on 2024-03-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_counseling'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingrecord',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_recorder', to='clinic.staffs'),
        ),
    ]
