# Generated by Django 4.2.9 on 2024-02-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_diagnosis_remove_consultationnotes_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemotePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(editable=False, max_length=20, unique=True, verbose_name='MRN')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Marital Status')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('tribe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tribe')),
                ('patient_type', models.CharField(max_length=100, verbose_name='Patient Type')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('occupation', models.CharField(max_length=100, verbose_name='Occupation')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Number')),
                ('date_of_first_employment', models.DateField(blank=True, null=True, verbose_name='Date of First Employment')),
                ('longtime_illness', models.CharField(max_length=100, verbose_name='Longtime Illness')),
                ('longtime_medication', models.CharField(max_length=100, verbose_name='Longtime Medication')),
                ('osha_certificate', models.BooleanField(default=False, verbose_name='OSHA Certificate')),
                ('date_of_osha_certification', models.DateField(blank=True, null=True, verbose_name='Date of OSHA Certification')),
                ('insurance', models.CharField(choices=[('Insured', 'Insured'), ('Uninsured', 'Uninsured')], max_length=100, verbose_name='Insurance')),
                ('insurance_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Company')),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Number')),
                ('emergency_contact_name', models.CharField(max_length=50, verbose_name='Emergency Contact Name')),
                ('emergency_contact_relation', models.CharField(max_length=20, verbose_name='Emergency Contact Relation')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_mobile', models.CharField(max_length=20, verbose_name='Emergency Contact Mobile')),
                ('life_style', models.CharField(max_length=100, verbose_name='Lifestyle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_health_condition', models.BooleanField(default=False, verbose_name='Has Health Condition')),
                ('health_condition_notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Health Condition Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_conditions', to='clinic.remotepatient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100, verbose_name='Condition')),
                ('relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Relationship')),
                ('comments', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_medical_history', to='clinic.remotepatient', verbose_name='Patient')),
            ],
        ),
    ]
