# Generated by Django 4.2.9 on 2024-03-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_patientsurgery_patientmedicationallergy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlifestylebehavior',
            old_name='behavior_name',
            new_name='weekly_exercise_frequency',
        ),
        migrations.RemoveField(
            model_name='patientlifestylebehavior',
            name='frequency',
        ),
        migrations.AddField(
            model_name='patientlifestylebehavior',
            name='alcohol_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientlifestylebehavior',
            name='healthy_diet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientlifestylebehavior',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientlifestylebehavior',
            name='stress_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientlifestylebehavior',
            name='sufficient_sleep',
            field=models.BooleanField(default=False),
        ),
    ]
