# Generated by Django 4.2.9 on 2024-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_remotepatient_patienthealthcondition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthealthcondition',
            name='has_health_condition',
        ),
        migrations.AddField(
            model_name='patienthealthcondition',
            name='health_condition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Health Condition'),
        ),
    ]
