# Generated by Django 4.2.9 on 2024-03-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_rename_behavior_name_patientlifestylebehavior_weekly_exercise_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicationallergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_allergies', to='clinic.remotepatient'),
        ),
    ]
