# Generated by Django 4.2.9 on 2024-02-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_remove_patienthealthcondition_has_health_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealthcondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_conditions', to='clinic.remotepatient', verbose_name='Patient'),
        ),
    ]
