# Generated by Django 4.2.9 on 2024-03-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_alter_patientmedicationallergy_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsurgery',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='patientsurgery',
            name='surgeon_name',
        ),
    ]
