# Generated by Django 4.2.9 on 2024-02-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_remove_remotepatientvisits_visit_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteprescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatient'),
        ),
    ]
