# Generated by Django 4.2.9 on 2024-02-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_alter_remoteprescription_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteConsultationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaints', models.TextField(blank=True, null=True)),
                ('history_of_presenting_illness', models.TextField(blank=True, null=True)),
                ('consultation_number', models.CharField(max_length=20, unique=True)),
                ('physical_examination', models.TextField(blank=True, null=True)),
                ('allergy_to_medications', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs')),
                ('final_diagnosis', models.ManyToManyField(blank=True, related_name='final_notes', to='clinic.diagnosis')),
                ('pathology', models.ManyToManyField(blank=True, to='clinic.pathodologyrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatient')),
                ('provisional_diagnosis', models.ManyToManyField(blank=True, related_name='provisional_notes', to='clinic.diagnosis')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits')),
            ],
        ),
    ]
