# Generated by Django 4.2.9 on 2024-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_remove_remotepatient_emergency_contact_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotepatient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
