# Generated by Django 4.2.9 on 2024-03-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_order_added_by_order_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulanceorder',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_data_recorder', to='clinic.staffs'),
        ),
    ]
