# Generated by Django 4.2.9 on 2024-02-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_remotepatientvital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotepatientvital',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits'),
        ),
    ]
