# Generated by Django 4.2.9 on 2024-03-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_ambulanceorder_data_recorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
