# Generated by Django 4.2.9 on 2024-03-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
