# Generated by Django 4.2.9 on 2024-01-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_healthissue_diagnostictest_pathology_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('collection_date', models.DateField()),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('processing', 'Processing'), ('analyzed', 'Analyzed')], max_length=20)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='clinic.diagnostictest')),
            ],
        ),
    ]
