# Generated by Django 4.2.9 on 2024-01-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
