# Generated by Django 4.2.9 on 2024-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_consultationnotes_visit_patientvital_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvital',
            name='weight',
            field=models.CharField(blank=True, help_text='weight', max_length=20, null=True),
        ),
    ]
