# Generated by Django 4.2.9 on 2024-03-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_ambulanceorder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotepatientvital',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, default=37.5, help_text='Temperature measurement in Celsius', max_digits=5, null=True),
        ),
    ]
