# Generated by Django 4.2.9 on 2024-02-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteconsultationnotes',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits'),
        ),
        migrations.AlterField(
            model_name='remotepatientvisits',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatient'),
        ),
    ]
