# Generated by Django 4.2.9 on 2024-03-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_remotepatientvital_dbp_remotepatientvital_sbp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlifestylebehavior',
            name='alcohol_consumption',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientlifestylebehavior',
            name='healthy_diet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientlifestylebehavior',
            name='smoking',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientlifestylebehavior',
            name='stress_management',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientlifestylebehavior',
            name='sufficient_sleep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientlifestylebehavior',
            name='weekly_exercise_frequency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
