# Generated by Django 4.2.9 on 2024-02-04 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_alter_sample_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyDiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.TextField(blank=True, null=True)),
                ('testing_date', models.DateField(blank=True, null=True)),
                ('conducted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostic_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.diagnostictest')),
                ('pathology_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_tests', to='clinic.pathodologyrecord')),
            ],
        ),
    ]
