# Generated by Django 4.2.9 on 2024-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_consultation_created_by_alter_consultation_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='appointment_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
