# Generated by Django 4.2.9 on 2024-02-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_pathologydiagnostictest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathodologyrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
