# Generated by Django 4.2.9 on 2024-03-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_alter_patientlifestylebehavior_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotepatientvital',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs'),
        ),
    ]
