# Generated by Django 4.2.9 on 2024-02-04 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_alter_pathodologyrecord_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='consultationfee',
            name='consultation_date',
        ),
        migrations.AddField(
            model_name='consultationfee',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.consultation'),
        ),
        migrations.AddField(
            model_name='consultationfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
