# Generated by Django 4.2.9 on 2024-03-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_remotepatientvital_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotepatientvital',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Respiratory rate in breaths per minute', null=True),
        ),
        migrations.AlterField(
            model_name='remotepatientvital',
            name='spo2',
            field=models.PositiveIntegerField(blank=True, help_text='SPO2 measurement in percentage', null=True),
        ),
    ]
