# Generated by Django 4.2.9 on 2024-03-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0023_procedure_procedure_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Ambulance', 'Ambulance'), ('Car', 'Car'), ('Van', 'Van'), ('Truck', 'Truck'), ('Motorcycle', 'Motorcycle')], max_length=100)),
                ('activities', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ambulance_type', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('days', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=100)),
                ('intubation', models.CharField(max_length=100)),
                ('pregnancy', models.CharField(max_length=100)),
                ('oxygen', models.CharField(max_length=100)),
                ('ambulance_type', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('ambulance_number', models.CharField(max_length=20, unique=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patientvisits')),
            ],
        ),
    ]
