# Generated by Django 4.2.9 on 2024-03-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_vehicle_ambulanceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs'),
        ),
    ]
