# Generated by Django 4.2.9 on 2024-03-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_healthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteprescription',
            name='issued',
            field=models.CharField(choices=[('issued', 'Issued'), ('not_issued', 'Not Issued')], default='not_issued', max_length=20),
        ),
        migrations.AddField(
            model_name='remoteprescription',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='remoteprescription',
            name='verified',
            field=models.CharField(choices=[('verified', 'Verified'), ('not_verified', 'Not Verified')], default='not_verified', max_length=20),
        ),
    ]
