# Generated by Django 4.2.9 on 2024-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0027_prescription_issued_prescription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='issued',
            field=models.CharField(choices=[('issued', 'Issued'), ('Not Issued', 'Not Issued')], default='Not Issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='verified',
            field=models.CharField(choices=[('verified', 'Verified'), ('Not Verified', 'Not Verified')], default='Not Verified', max_length=20),
        ),
    ]
