# Generated by Django 4.2.9 on 2024-03-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_ambulanceorder_created_at_ambulanceorder_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='AmbulanceVehicleOrder',
        ),
    ]
