# Generated by Django 4.2.9 on 2024-03-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0030_rename_vehicle_ambulancevehicleorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancevehicleorder',
            name='ambulance_type',
        ),
        migrations.AddField(
            model_name='ambulancevehicleorder',
            name='ambulance_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancevehicleorder',
            name='activities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancevehicleorder',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancevehicleorder',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancevehicleorder',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancevehicleorder',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancevehicleorder',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancevehicleorder',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
