# Generated by Django 4.2.9 on 2024-02-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0030_reagentusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_date', models.DateField()),
                ('control_type', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('lab_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs')),
            ],
        ),
    ]
