# Generated by Django 4.2.9 on 2024-02-11 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0031_qualitycontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='MedicalRecordConsultation',
        ),
    ]
