# Generated by Django 4.2.9 on 2024-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0032_prescriptionfrequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
