# Generated by Django 4.2.9 on 2024-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0032_healthissue_created_at_healthissue_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinventory',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
