# Generated by Django 4.2.9 on 2024-02-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0033_medicineinventory_total_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='company',
            new_name='payment_form',
        ),
    ]
