# Generated by Django 4.2.9 on 2024-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0034_rename_company_patients_payment_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='insurance_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='payment_form',
            field=models.CharField(choices=[('cash', 'Cash'), ('insurance', 'Insurance')], max_length=255),
        ),
    ]
