# Generated by Django 4.2.9 on 2024-02-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0035_patients_authorization_code_patients_insurance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='covarage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
