# Generated by Django 4.2.9 on 2024-03-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0036_ambulanceactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='website',
            field=models.URLField(default='http://example.com'),
        ),
    ]
