# Generated by Django 4.2.9 on 2024-02-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0036_service_covarage_alter_service_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='authorization_code',
        ),
    ]
