# Generated by Django 4.2.9 on 2024-02-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0037_remove_patients_authorization_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vst', models.CharField(editable=False, max_length=20, unique=True)),
                ('visit_type', models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency'), ('Referral', 'Referral'), ('Follow up', 'Follow up')], max_length=15)),
                ('visit_reason', models.TextField(blank=True, null=True)),
                ('referral_number', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_service', models.CharField(max_length=50)),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_name', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_scheme', models.CharField(blank=True, max_length=50, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
        ),
    ]
