# Generated by Django 4.2.9 on 2024-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0037_insurancecompany_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cost',
            new_name='cash_cost',
        ),
        migrations.AddField(
            model_name='service',
            name='insurance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='nhif_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
