# Generated by Django 4.2.9 on 2024-03-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0039_medicineroute_medicineunitmeasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='medicine',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='cash_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='nhif_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='MedicineTransaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
