# Generated by Django 4.2.9 on 2024-04-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0040_remove_transaction_medicines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryPhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_airway', models.CharField(blank=True, max_length=100)),
                ('notpatient_explanation', models.TextField(blank=True)),
                ('breathing', models.CharField(blank=True, max_length=100)),
                ('normal_breathing', models.TextField(blank=True)),
                ('abnormal_breathing', models.CharField(blank=True, max_length=100)),
                ('circulating', models.CharField(blank=True, max_length=100)),
                ('normal_circulating', models.TextField(blank=True)),
                ('abnormal_circulating', models.CharField(blank=True, max_length=100)),
                ('gcs', models.CharField(blank=True, max_length=100)),
                ('rbg', models.CharField(blank=True, max_length=100)),
                ('pupil', models.CharField(blank=True, max_length=100)),
                ('pain_score', models.CharField(blank=True, max_length=100)),
                ('avpu', models.CharField(blank=True, max_length=100)),
                ('exposure', models.CharField(blank=True, max_length=100)),
                ('normal_exposure', models.CharField(blank=True, max_length=100)),
                ('abnormal_exposure', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits')),
            ],
        ),
        migrations.CreateModel(
            name='ChiefComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_complaint', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.healthrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits')),
            ],
        ),
    ]
