# Generated by Django 4.2.9 on 2024-04-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0044_alter_primaryphysicalexamination_abnormal_breathing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryphysicalexamination',
            name='airway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
