# Generated by Django 4.2.9 on 2024-04-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0048_remoteambulanceactivity_remoteambulanceroute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteservice',
            name='price',
        ),
    ]
