# Generated by Django 4.2.9 on 2024-04-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0049_remove_remoteservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotelaboratoryorder',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.remoteservice'),
        ),
        migrations.AlterField(
            model_name='remoteprocedure',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.remoteservice'),
        ),
    ]
