# Generated by Django 4.2.9 on 2024-04-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0050_alter_remotelaboratoryorder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathodologyrecord',
            name='related_diseases',
        ),
        migrations.AddField(
            model_name='remotereferral',
            name='nature_of_referral',
            field=models.CharField(choices=[('med_evac', 'Med Evac'), ('referral', 'Referral')], default='referral', max_length=20),
        ),
        migrations.AddField(
            model_name='remotereferral',
            name='transport_model',
            field=models.CharField(choices=[('ground_ambulance', 'Ground Ambulance'), ('air_ambulance', 'Air Ambulance'), ('private_vehicle', 'Private Vehicle'), ('self_transport', 'Self Transport'), ('company_walking', 'Company Walking'), ('walking', 'Walking'), ('motorcycle', 'Motorcycle'), ('others', 'Others'), ('unknown', 'Unknown')], default='ground_ambulance', max_length=50),
        ),
    ]
