# Generated by Django 4.2.9 on 2024-04-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0051_remove_pathodologyrecord_related_diseases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='type_of_illness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remoteconsultationnotes',
            name='history_of_presenting_illness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
