# Generated by Django 4.2.9 on 2024-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0052_remoteconsultationnotes_type_of_illness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='nature_of_current_illness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remoteconsultationnotes',
            name='history_of_presenting_illness',
            field=models.TextField(blank=True, null=True),
        ),
    ]
