# Generated by Django 4.2.9 on 2024-04-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0054_alter_remotereferral_nature_of_referral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotereferral',
            name='nature_of_referral',
            field=models.CharField(choices=[('Med Evac', 'Med Evac'), ('Referred', 'Referral')], default='Referred', max_length=20),
        ),
        migrations.AlterField(
            model_name='remotereferral',
            name='transport_model',
            field=models.CharField(choices=[('Ground Ambulance', 'Ground Ambulance'), ('Air Ambulance', 'Air Ambulance'), ('Private Vehicle', 'Private Vehicle'), ('Self Transport', 'Self Transport'), ('Company Walking', 'Company Walking'), ('Walking', 'Walking'), ('Motorcycle', 'Motorcycle'), ('Others', 'Others'), ('Unknown', 'Unknown')], default='Ground Ambulance', max_length=50),
        ),
    ]
