# Generated by Django 4.2.9 on 2024-04-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0055_alter_remotereferral_nature_of_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
