# Generated by Django 4.2.9 on 2024-04-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0057_remotemedicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotemedicine',
            name='drug_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
