# Generated by Django 4.2.9 on 2024-04-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0058_alter_remotemedicine_drug_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotemedicine',
            name='total_buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
