# Generated by Django 4.2.9 on 2024-04-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0059_remotemedicine_total_buying_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteprescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotemedicine'),
        ),
    ]
