# Generated by Django 4.2.9 on 2024-04-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0062_bankaccount_client_deductionorganization_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'verbose_name': ' Salary Payment'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=20),
        ),
    ]
