# Generated by Django 4.2.9 on 2024-04-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0063_alter_salarypayment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarypayment',
            name='amount',
        ),
    ]
