# Generated by Django 4.2.9 on 2024-05-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0064_remove_salarypayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='work_place',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
