# Generated by Django 4.2.9 on 2024-05-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0065_staffs_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='work_place',
            field=models.CharField(blank=True, choices=[('resa', 'Resa'), ('kahama', 'Kahama')], max_length=50),
        ),
    ]
