# Generated by Django 4.2.9 on 2024-05-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0066_alter_staffs_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-Binary'), ('prefer-not-to-say', 'Prefer Not to Say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='profession',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('radiologist', 'Radiologist'), ('lab_technician', 'Lab Technician'), ('receptionist', 'Receptionist'), ('physiotherapist', 'Physiotherapist'), ('accountant', 'Accountant'), ('security_guard', 'Security Guard'), ('chef', 'Chef'), ('cleaner', 'Cleaner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('physiotherapist', 'Physiotherapist'), ('labTechnician', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]
