# Generated by Django 4.2.9 on 2024-05-06 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0067_alter_staffs_gender_alter_staffs_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsurgery',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_patient_surgery', to='clinic.remotepatient'),
        ),
        migrations.AlterField(
            model_name='service',
            name='coverage',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Insurance', 'Insurance')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_service',
            field=models.CharField(blank=True, choices=[('Procedure', 'Procedure'), ('Laboratory', 'Laboratory'), ('Imaging', 'Imaging'), ('Drugs', 'Drugs'), ('Test', 'Test'), ('Consultation', 'Consultation'), ('Education', 'Education'), ('Examination', 'Examination'), ('Vaccination', 'Vaccination'), ('Medication', 'Medication'), ('Therapy', 'Therapy'), ('Rehabilitation', 'Rehabilitation'), ('Rental', 'Rental'), ('Plan', 'Plan')], max_length=200, null=True),
        ),
    ]
