# Generated by Django 4.2.9 on 2024-05-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0068_alter_patientsurgery_patient_alter_service_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteconsultation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_created_consultations', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remoteconsultation',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits'),
        ),
    ]
