# Generated by Django 4.2.9 on 2024-05-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0070_alter_patientmedicationallergy_patient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientMedicationAllergy',
        ),
    ]
