# Generated by Django 4.2.9 on 2024-05-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0071_delete_patientmedicationallergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicationAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_medicine', to='clinic.remotemedicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_medication_allergies', to='clinic.remotepatient')),
            ],
        ),
        migrations.DeleteModel(
            name='RemotePatientMedicationAllergy',
        ),
    ]
