# Generated by Django 4.2.9 on 2024-05-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0072_patientmedicationallergy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlifestylebehavior',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatient'),
        ),
    ]
