# Generated by Django 4.2.9 on 2024-05-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0073_alter_patientlifestylebehavior_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteprocedure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='procedure_images/'),
        ),
    ]
