# Generated by Django 4.2.9 on 2024-05-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0074_remoteprocedure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
