# Generated by Django 4.2.9 on 2024-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0075_staffs_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='payment_form',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Insurance', 'Insurance')], max_length=255),
        ),
    ]
