# Generated by Django 4.2.9 on 2024-05-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0077_rename_name_medicine_drug_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(default=12345, max_length=20, unique=True),
        ),
    ]
