# Generated by Django 4.2.9 on 2024-05-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0079_alter_diagnostictest_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_of_order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
