# Generated by Django 4.2.9 on 2024-04-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_remove_familymedicalhistory_patient_and_more'),
        ('kahamahmis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotereferral',
            name='consultation',
        ),
        migrations.AddField(
            model_name='remotereferral',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs'),
        ),
        migrations.AlterField(
            model_name='remotereferral',
            name='source_location',
            field=models.CharField(default='resa medical hospital', help_text='Source location of the patient', max_length=255),
        ),
    ]
