# Generated by Django 4.2.9 on 2024-04-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_remove_familymedicalhistory_patient_and_more'),
        ('kahamahmis', '0003_remove_remoteprocedure_consultation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RemoteImagingRecord',
            new_name='RemoteObservationRecord',
        ),
    ]
