# Generated by Django 4.2.9 on 2024-04-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_remove_familymedicalhistory_patient_and_more'),
        ('kahamahmis', '0004_rename_remoteimagingrecord_remoteobservationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteobservationrecord',
            name='imaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.service'),
        ),
    ]
