# Generated by Django 4.2.9 on 2024-04-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahamahmis', '0006_alter_remotelaboratoryorder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='allergy_to_medications',
        ),
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='chief_complaints',
        ),
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='physical_examination',
        ),
        migrations.AlterField(
            model_name='remoteconsultationnotes',
            name='final_diagnosis',
            field=models.ManyToManyField(blank=True, related_name='final_diagnosis', to='kahamahmis.diagnosis'),
        ),
        migrations.AlterField(
            model_name='remoteconsultationnotes',
            name='provisional_diagnosis',
            field=models.ManyToManyField(blank=True, related_name='provisional_diagnosis', to='kahamahmis.diagnosis'),
        ),
    ]
