# Generated by Django 4.2.9 on 2024-04-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_remove_familymedicalhistory_patient_and_more'),
        ('kahamahmis', '0008_alter_remoteprescription_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteprescription',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs'),
        ),
    ]
