# Generated by Django 4.2.9 on 2024-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahamahmis', '0009_remoteprescription_entered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='final_diagnosis',
        ),
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='provisional_diagnosis',
        ),
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='final_diagnosis_notes',
            field=models.ManyToManyField(blank=True, related_name='final_diagnosis_notes', to='kahamahmis.diagnosis'),
        ),
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='provisional_diagnosis_notes',
            field=models.ManyToManyField(blank=True, related_name='provisional_diagnosis_notes', to='kahamahmis.diagnosis'),
        ),
    ]
