# Generated by Django 4.2.9 on 2024-04-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahamahmis', '0010_remove_remoteconsultationnotes_final_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='final_diagnosis_notes',
        ),
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='provisional_diagnosis_notes',
        ),
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='final_diagnosis',
            field=models.ManyToManyField(blank=True, related_name='final_diagnosis', to='kahamahmis.diagnosis'),
        ),
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='provisional_diagnosis',
            field=models.ManyToManyField(blank=True, related_name='provisional_diagnosis', to='kahamahmis.diagnosis'),
        ),
    ]
