# Generated by Django 4.2.9 on 2024-04-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kahamahmis', '0011_remove_remoteconsultationnotes_final_diagnosis_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteprocedure',
            name='cost',
        ),
    ]
