# Generated by Django 4.2.9 on 2024-04-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kahamahmis', '0012_remove_remoteprocedure_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotelaboratoryorder',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='remotelaboratoryorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='remotelaboratoryorder',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='remotelaboratoryorder',
            name='order_date',
        ),
    ]
