# Generated by Django 4.2.9 on 2024-04-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kahamahmis', '0013_remove_remotelaboratoryorder_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteobservationrecord',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='remoteobservationrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='remoteobservationrecord',
            name='image',
        ),
        migrations.RemoveField(
            model_name='remoteobservationrecord',
            name='imaging',
        ),
        migrations.RemoveField(
            model_name='remoteobservationrecord',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='remoteobservationrecord',
            name='result',
        ),
    ]
