# Generated by Django 4.2.9 on 2024-04-08 11:22

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kahamahmis', '0015_remove_remoteobservationrecord_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteobservationrecord',
            name='observation_notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
