# Generated by Django 4.2.9 on 2024-04-08 12:05

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_remove_familymedicalhistory_patient_and_more'),
        ('kahamahmis', '0016_alter_remoteobservationrecord_observation_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotecounseling',
            name='counselor',
        ),
        migrations.RemoveField(
            model_name='remotecounseling',
            name='description',
        ),
        migrations.RemoveField(
            model_name='remotecounseling',
            name='topic',
        ),
        migrations.AddField(
            model_name='remotecounseling',
            name='counselling_notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remotecounseling',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs'),
        ),
    ]
