# Generated by Django 4.2.9 on 2024-04-08 12:24

from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kahamahmis', '0017_remove_remotecounseling_counselor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remotereferral',
            old_name='doctor',
            new_name='data_recorder',
        ),
        migrations.RemoveField(
            model_name='remotereferral',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='remotereferral',
            name='referral_date',
        ),
        migrations.AddField(
            model_name='remotereferral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remotereferral',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
