# Generated by Django 4.2.9 on 2024-04-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_remove_familymedicalhistory_patient_and_more'),
        ('kahamahmis', '0019_remotedischargesnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='final_diagnosis',
        ),
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='provisional_diagnosis',
        ),
        migrations.CreateModel(
            name='RemotePatientDiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs')),
                ('final_diagnosis', models.ManyToManyField(related_name='final_diagnosis_records', to='kahamahmis.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kahamahmis.remotepatient')),
                ('provisional_diagnosis', models.ManyToManyField(related_name='provisional_diagnosis_records', to='kahamahmis.diagnosis')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kahamahmis.remotepatientvisits')),
            ],
        ),
    ]
