# Generated by Django 4.2.9 on 2024-04-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0047_remove_familymedicalhistory_patient_and_more'),
        ('kahamahmis', '0020_remove_remoteconsultationnotes_final_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotepatientdiagnosisrecord',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs'),
        ),
    ]
